# Generated by Django 3.2.15 on 2022-10-02 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_content', models.FileField(blank=True, null=True, upload_to='content', verbose_name='app_files')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('short', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('level', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='university', verbose_name='university_image')),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_country', to='global.country')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('level', models.CharField(blank=True, max_length=128, null=True)),
                ('user_type', models.CharField(blank=True, default='teacher', max_length=64, null=True)),
                ('status', models.BooleanField(default=True)),
                ('password_change', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_qualification', to='global.qualification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, default='student', max_length=64, null=True)),
                ('password_change', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('guardian_mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('school', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('assigned_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teacher', to='global.teacher')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_qualification', to='global.qualification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=26, null=True)),
                ('acceptance', models.BooleanField(blank=True, default=False, null=True)),
                ('passport', models.CharField(blank=True, max_length=128, null=True)),
                ('father', models.CharField(blank=True, max_length=128, null=True)),
                ('mother', models.CharField(blank=True, max_length=128, null=True)),
                ('father_mobile', models.CharField(blank=True, max_length=128, null=True)),
                ('mother_mobile', models.CharField(blank=True, max_length=128, null=True)),
                ('parent_email', models.EmailField(blank=True, max_length=128, null=True)),
                ('street_1', models.CharField(blank=True, max_length=128, null=True)),
                ('street_2', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('dob', models.CharField(blank=True, max_length=128, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=128, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='photos', verbose_name='app_files')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_personal_info', to='global.student')),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_content', to='global.content')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory', to='global.directory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_student', to='global.student')),
            ],
        ),
    ]
