# Generated by Django 3.2.15 on 2022-10-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='teacher_photos', verbose_name='teacher_image'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='student_photos', verbose_name='student_image'),
        ),
    ]
