# Generated by Django 3.2.15 on 2022-10-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0002_auto_20221002_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
