# Generated by Django 3.2.15 on 2022-10-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0003_auto_20221003_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='taken_care',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
