# Generated by Django 3.2.16 on 2022-10-11 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0005_auto_20221009_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assigned_teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teacher', to='global.teacher'),
        ),
    ]
