# Generated by Django 3.2.15 on 2022-10-11 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0006_alter_student_assigned_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUniversityIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_university', to='global.student')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uni_student', to='global.university')),
            ],
        ),
    ]
