# Generated by Django 3.2.16 on 2022-10-26 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0007_studentuniversityindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCountryIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctry_student', to='global.country')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_country', to='global.student')),
            ],
        ),
    ]
