# Generated by Django 3.2.18 on 2023-04-09 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0011_subscription_subscriptioncode_usersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('detail', models.TextField()),
                ('subscriptionReq', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LectureMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('detail', models.TextField()),
                ('videoUrl', models.CharField(max_length=256)),
                ('thumb', models.FileField(blank=True, null=True, upload_to='free_lectures', verbose_name='free_lecture_image')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('detail', models.TextField()),
                ('videoUrl', models.CharField(max_length=256)),
                ('thumb', models.FileField(blank=True, null=True, upload_to='lectures', verbose_name='lecture_image')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.course')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('detail', models.TextField()),
                ('thumb', models.FileField(blank=True, null=True, upload_to='articles', verbose_name='article_image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.articlecategory')),
            ],
        ),
    ]
