# Generated by Django 3.2.16 on 2023-04-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0013_auto_20230409_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coursetype',
            field=models.CharField(max_length=256, null='True'),
            preserve_default='True',
        ),
    ]
