# Generated by Django 3.2.16 on 2023-04-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0015_auto_20230418_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumb',
            field=models.FileField(blank=True, null=True, upload_to='courses', verbose_name='course_image'),
        ),
    ]
