# Generated by Django 3.2.18 on 2023-04-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0019_auto_20230418_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='zipContent',
            field=models.FileField(blank=True, null=True, upload_to='interactives', verbose_name='interactives'),
        ),
    ]
