# Generated by Django 3.2.18 on 2023-04-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0020_alter_lecture_zipcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='zipurl',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
