# Generated by Django 3.2.18 on 2023-04-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0021_lecture_zipurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsciptionkey',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subsciptionkey',
            name='shortKey',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
