# Generated by Django 3.2.18 on 2023-05-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0023_studentenlistedcourse_studentwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
    ]
