# Generated by Django 3.2.18 on 2023-05-29 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('global', '0024_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('bundleType', models.CharField(blank=True, max_length=64, null=True)),
                ('fee', models.FloatField()),
                ('subscriptionReq', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('detail', models.TextField(blank=True, null=True)),
                ('subjectType', models.CharField(max_length=256)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('keywords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.keywords')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.level')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('detail', models.TextField(blank=True, null=True)),
                ('subcriptionType', models.BooleanField(default=True)),
                ('fee', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('keywords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.keywords')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.subject')),
            ],
        ),
        migrations.AlterField(
            model_name='studentenlistedcourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='global.course'),
        ),
        migrations.CreateModel(
            name='TopicContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('detail', models.TextField()),
                ('videoUrl', models.CharField(blank=True, max_length=256, null=True)),
                ('zipContent', models.FileField(blank=True, null=True, upload_to='topicZips', verbose_name='topicZips')),
                ('zipurl', models.CharField(blank=True, max_length=256, null=True)),
                ('thumb', models.FileField(blank=True, null=True, upload_to='topicthumbs', verbose_name='topic_image')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.topic')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnlistedBundles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('bundles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='global.bundle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bundle',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.topic'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
