# Generated by Django 3.2.18 on 2023-05-29 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('global', '0025_auto_20230529_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, default='institute', max_length=64, null=True)),
                ('status', models.BooleanField(default=True)),
                ('password_change', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstituteTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='global.userinstitute')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='global.userinstitute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.student')),
            ],
        ),
        migrations.CreateModel(
            name='BundleWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptionKey', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('shortKey', models.CharField(max_length=12, null=True, unique=True)),
                ('amount', models.FloatField()),
                ('active_status', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.bundle')),
            ],
        ),
    ]
