# Generated by Django 3.2.18 on 2023-05-30 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0026_auto_20230529_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='videoUrl',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='zipContent',
            field=models.FileField(blank=True, null=True, upload_to='interactives', verbose_name='interactives'),
        ),
        migrations.AddField(
            model_name='topic',
            name='zipurl',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='keywords',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='global.keywords'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='keywords',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='global.keywords'),
        ),
    ]
