# Generated by Django 3.2.18 on 2023-05-30 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0027_auto_20230530_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='videoUrl',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='zipContent',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='zipurl',
        ),
        migrations.AddField(
            model_name='subject',
            name='thumb',
            field=models.FileField(blank=True, null=True, upload_to='subjectthumbs', verbose_name='subject_image'),
        ),
        migrations.AddField(
            model_name='topic',
            name='thumb',
            field=models.FileField(blank=True, null=True, upload_to='topicthumbnails', verbose_name='topic_thumb_image'),
        ),
        migrations.CreateModel(
            name='TopicExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipContent', models.FileField(blank=True, null=True, upload_to='topicexercise', verbose_name='topicexercise')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.topic')),
            ],
        ),
    ]
