# Generated by Django 3.2.18 on 2023-05-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0028_auto_20230530_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicexercise',
            old_name='zipContent',
            new_name='exercises',
        ),
    ]
