# Generated by Django 3.2.18 on 2023-05-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0031_rename_exercises_topicexercise_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='user',
        ),
    ]
