# Generated by Django 3.2.16 on 2023-05-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0033_auto_20230530_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenlistedbundles',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
