# Generated by Django 3.2.16 on 2023-06-01 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0034_studentenlistedbundles_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField(blank=True, null=True)),
                ('articleimage', models.FileField(blank=True, null=True, upload_to='article_imgs', verbose_name='articleImg')),
                ('instruction', models.TextField(blank=True, null=True)),
                ('instructionimage', models.FileField(blank=True, null=True, upload_to='instruction_imgs', verbose_name='instructionImg')),
                ('shortdescription', models.TextField(blank=True, null=True)),
                ('instructional_video', models.CharField(blank=True, max_length=512, null=True)),
                ('theory_video', models.CharField(blank=True, max_length=512, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.topic')),
            ],
        ),
    ]
