# Generated by Django 3.2.18 on 2023-07-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0035_topicinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('detail', models.TextField(blank=True, null=True)),
                ('intZip', models.FileField(blank=True, null=True, upload_to='interactiveZips', verbose_name='interactiveZips')),
                ('intUrl', models.CharField(blank=True, max_length=256, null=True)),
                ('thumb', models.FileField(blank=True, null=True, upload_to='intThumbs', verbose_name='intThumbs')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
