# Generated by Django 3.2.18 on 2023-09-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0038_topicqualifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicqualifications',
            old_name='qualifcation',
            new_name='qualification',
        ),
    ]
