# Generated by Django 3.2.18 on 2023-09-11 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0039_rename_qualifcation_topicqualifications_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('thumb', models.FileField(blank=True, null=True, upload_to='topicmasterthumbnails', verbose_name='topic_masther_thumb_image')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('keywords', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='global.keywords')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.subject')),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='global.topicmaster'),
            preserve_default=False,
        ),
    ]
