# Generated by Django 3.2.18 on 2023-09-11 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0040_auto_20230911_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.board')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global.topic')),
            ],
        ),
    ]
